---
- name: Install apps for grafana
  apt:
   pkg:
    - apt-transport-https
    - software-properties-common
- name: Add grafana key
  ansible.builtin.apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present
- name: Add repo for grafana
  ansible.builtin.apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present
- name: update cache
  apt:
    update_cache: yes
- name: Install  grafana
  apt:
   pkg:
    - grafana
    

   
- name: reset admin pass
  ansible.builtin.command:
   cmd: grafana-cli admin reset-admin-password '{{grafana_pass}}'
   
- name: grafana-server datasources confs
  ansible.builtin.template:
   src: datasource.yaml
   dest: /etc/grafana/provisioning/datasources/datasource.yaml
  notify: 
   - restart grafana-server

   
- name: grafana-server json confs
  ansible.builtin.template:
   src: roles/grafana/templates/dashboards.yaml
   dest: /etc/grafana/provisioning/dashboards/dashboards.yaml
  notify: 
   - restart grafana-server

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /var/lib/grafana/dashboards
    state: directory
    mode: '0755'
  notify: 
   - restart grafana-server
- name: grafana-server jsonfile confs
  ansible.builtin.copy:
   src: roles/grafana/files/main.json
   dest: /var/lib/grafana/dashboards/main.json
  notify: 
   - restart grafana-server
- name: grafana-server jsonfile confs
  ansible.builtin.copy:
   src: roles/grafana/files/syslog.json
   dest: /var/lib/grafana/dashboards/syslog.json
  notify: 
   - restart grafana-server
- name: grafana-server jsonfile confs
  ansible.builtin.copy:
   src: roles/grafana/files/syslog.json
   dest: /var/lib/grafana/dashboards/mysql.json
  notify: 
   - restart grafana-server
- name: grafana-server service start and conf
  ansible.builtin.service:
   name: grafana-server
   enabled: yes
   state: started

- name: grafana-server template confs
  ansible.builtin.template:
   src: roles/grafana/templates/grafana.ini
   dest: /etc/grafana/grafana.ini
  notify: 
   - restart grafana-server
