---
- name: Add backup user
  ansible.builtin.user:
    name: backup
    group: backup
    home: /home/backup
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
    shell: /bin/bash
- name: Create /opt/agama
  ansible.builtin.file:
   path: /home/backup/restore
   owner: backup
   group: backup
   state: directory
- name: Install duplicity
  apt:
   name: 
   - duplicity
- name: template backup server known_hosts
  ansible.builtin.template:
   src: roles/backup/templates/known_hosts
   dest: /home/backup/.ssh/known_hosts
   owner: backup
   group: backup
