{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "keepalived_vrrp_state",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "keepalived_vrrp_state" }
   ]
  },
  {
   "title": "haproxy_server_up",
   "type": "stat",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "haproxy_server_up" }
   ]
  },
  {
   "title": "haproxy",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "haproxy_up" }
   ]
  },
  {
   "title": "CPULoad",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    { "expr": "node_cpu_seconds_total" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysql_up" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_up" }
   ]
  },
  {
   "title": "Bind",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bind_up" }
   ]
  }
 ]
}