---
- name: restart 2
  community.mysql.mysql_replication:
    mode: "{{ item }}"
    primary_host: "{{ mysql_host }}"
    primary_user: "{{ replica_user }}"
    primary_password: "{{ replica_sql_pass }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  loop:
    - stopreplica
    - changeprimary
    - resetreplica
    - startreplica
  when: inventory_hostname != mysql_host
  no_log: true

- name: Restart pinger
  ansible.builtin.service:
   name: pinger
   state: restarted

