global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    scrape_timeout: 5s
    metrics_path: /prometheus/metrics
    static_configs:
      - targets: ['localhost:9090']

  - job_name: linux
    static_configs:
      - targets:
        {% for host in groups['all'] %}
       - '{{ host }}:9100'
        {% endfor %}
        
  - job_name: bind9
    static_configs:
      - targets:
        {% for host in groups['db_servers'] %}
       - '{{ host }}:9119'
        {% endfor %}
        
  - job_name: mysql
    static_configs:
      - targets:
        {% for host in groups['db_servers'] %}
       - '{{ host }}:9104'
        {% endfor %}
        
  - job_name: nginx
    static_configs:
      - targets:
        {% for host in groups['all'] %}
       - '{{ host }}:9113'
        {% endfor %}
        
  - job_name: influxbd
    static_configs:
      - targets:
        {% for host in groups['web_servers'] %}
       - '{{ host }}:9424'
        {% endfor %}

  - job_name: haproxy
    static_configs:
      - targets:
        {% for host in groups['all'] %}
       - '{{ host }}:9101'
        {% endfor %}

  - job_name: keepalived
    static_configs:
      - targets:
        {% for host in groups['all'] %}
       - '{{ host }}:9165'
        {% endfor %}
