---
- name: Create a directory for mysql backup
  ansible.builtin.file:
    path: /home/backup/mysql
    state: directory
    owner: backup
    group: backup
- name: Create user backup
  community.mysql.mysql_user:
    name: backup
    password: "{{ mysql_exporter_pass }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    host: "%"
    priv: 
     '*.*': 'LOCK TABLES,SELECT'
  notify: restart mysql
  no_log: true

- name: copy my.cnf
  ansible.builtin.template:
   src: roles/mysql_backup/templates/my.cnf
   dest: /home/backup/.my.cnf
   mode: '400'
   owner: backup
- name: copy cron tab file
  ansible.builtin.template:
   src: roles/mysql_backup/files/mysql-backup
   dest: /etc/cron.d/mysql-backup
  
