{
 "title": "mySql",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "mysql_global_variables_read_only",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_read_only"
    }
   ]
  },
  {
   "title": "mysql_slave_status_slave_sql_running",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_sql_running"
    }
   ]
  },
  {
   "title": "mysql_slave_status_slave_io_running",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_io_running"
    }
   ]
  },
  {
   "title": "mysql_global_variables_server_id",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_server_id\n"
    }
   ]
  },
  {
   "title": "mysql_global_status_commands_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "mysql_global_status_commands_total"
    }
   ]
  }
 ]
}