apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    #uid: my_unique_uid
    url: http://LeonidVagulin-1:9090/prometheus
    password:
    user:
    database:
    isDefault: true
    version: 1
    editable: false

  - name: InfluxDB-latency
    type: influxdb
    access: proxy
    orgId: 1
    #uid: my_unique_uid
    url: http://LeonidVagulin-1:8086
    password:
    user:
    database: latency
    isDefault: false
    version: 1
    editable: false

  - name: InfluxDB-telegraf
    type: influxdb
    access: proxy
    orgId: 1
    url: http://LeonidVagulin-1:8086
    password:
    user:
    database: telegraf
    isDefault: false
    version: 1
    editable: false
